

server:
  port: 8080

spring:
  datasource:
    password: manager
    url: jdbc:mysql://localhost:3306/elderly_care_app
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: DEBUG      
            

        
        
        

           